### ISSUE TITLE
【求助】使用免费版的17monipdb.datx库，解析出现错误，请帮忙看看是什么问题？

### ISSUE THREAD

**Issue by davidhefan** [ipipdotnet/datx-java#1]
![image](https://user-images.githubusercontent.com/13231750/40214646-793bfd52-5a8e-11e8-889a-657677207b60.png)
len是负值
![image](https://user-images.githubusercontent.com/13231750/40214627-636c347e-5a8e-11e8-9b97-00af67eb8bba.png)

**Comment by ilsanbao** [comment]
@davidhefan 请使用 City 类调用
